steps:
  - name: "gcr.io/cloud-builders/docker"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        docker build \
          --build-arg NEXT_PUBLIC_API_URL=${_NEXT_PUBLIC_API_URL} \
          -f Dockerfile \
          -t gcr.io/$PROJECT_ID/kininaru-clip-front:$COMMIT_SHA .

  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/kininaru-clip-front:$COMMIT_SHA"]

  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - "run"
      - "deploy"
      - "kininaru-clip-front"
      - "--image"
      - "gcr.io/$PROJECT_ID/kininaru-clip-front:$COMMIT_SHA"
      - "--region"
      - "${_DEPLOY_REGION}"
images:
  - "gcr.io/$PROJECT_ID/kininaru-clip-front:$COMMIT_SHA"
timeout: 900s

options:
  logging: CLOUD_LOGGING_ONLY
