import { Providers } from "./providers";
export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout(props: { children: React.ReactNode }) {
  const { children } = props;
  return (
    <html suppressHydrationWarning>
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
