services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
    environment:
      - GO_ENV=development
      - DB_HOST=postgresql
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=db
      - DB_PORT=5432
      - PYTHON_SERVER_BASE_URL=http://ai-engine:8000
    networks:
      - app-network
    depends_on:
      - postgresql

  ai-engine:
    build:
      context: ./ai_engine
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./ai_engine:/app
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - node_modules:/app/node_modules
    environment:
      - NODE_ENV=development
    networks:
      - app-network
    depends_on:
      - api

  swagger-ui:
    image: swaggerapi/swagger-ui:latest
    environment:
      SWAGGER_JSON: /api/api-document.yaml
    volumes:
      - ./docs/api-document.yaml:/api/api-document.yaml:ro
    ports:
      - "127.0.0.1:8081:8080"

  postgresql:
    image: postgres:16
    platform: linux/amd64
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: db
      TZ: "Asia/Tokyo"
    volumes:
      - ./postgres/postgres_init:/docker-entrypoint-initdb.d
      - db-data:/var/lib/postgresql/data
    networks:
      - app-network

  pgadmin4:
    image: dpage/pgadmin4:8.4
    ports:
      - 80:80
    volumes:
      - pgadmin-data:/var/lib/pgadmin
      - ./postgres/config/servers.json:/pgadmin4/servers.json
    environment:
      PGADMIN_DEFAULT_EMAIL: user@example.com
      PGADMIN_DEFAULT_PASSWORD: password
      PGADMIN_CONFIG_SERVER_MODE: "False"
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False"
    networks:
      - app-network
    depends_on:
      - postgresql

volumes:
  db-data:
  node_modules:
  pgadmin-data:

networks:
  app-network:
    driver: bridge
