openapi: "3.0.2"
info:
  title: "kininaru_clip_API"
  version: "2.0.0"
servers:
  - url: "http://localhost:8080"
  - url: "http://localhost:3000"
paths:
  /events:
    post:
      tags:
        - "events"
      summary: "Create a new event"
      operationId: "createEvent"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/createEventInput"
      responses:
        "200":
          description: "Event created"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/createEventResponse"

components:
  schemas:
    createEventInput:
      type: "object"
      properties:
        title:
          type: "string"
        url:
          type: "string"
      required:
        - "title"
    createEventResponse:
      type: "object"
      properties:
        id:
          type: "string"
        title:
          type: "string"
        url:
          type: "string"
        createdAt:
          type: "string"
          format: "date-time"
        updatedAt:
          type: "string"
          format: "date-time"
