openapi: "3.0.2"
info:
  title: "kininaru_clip_API"
  version: "2.0.0"
servers:
  - url: "http://localhost:8080"
  - url: "http://localhost:3000"
paths:
  /events:
    post:
      tags:
        - "events"
      summary: "Create a new event"
      operationId: "createEvent"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/createEventInput"
      responses:
        "200":
          description: "Event created"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/createEventResponse"

  /events/{eventId}/users:
    post:
      tags:
        - "users"
      summary: "Create Users"
      operationId: "createUsers"
      description: "指定したイベントに複数のユーザーを登録する"
      parameters:
        - in: path
          name: eventId
          required: true
          description: "イベントの一意な識別子"
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              description: "作成するユーザーの入力情報の配列"
              items:
                type: object
                description: "ユーザーの入力情報"
                properties:
                  name:
                    type: string
                    description: "ユーザーの名前"
                required:
                  - name
              example:
                - name: "山田花子"
      responses:
        "200":
          description: "Users created successfully"
          content:
            application/json:
              schema:
                type: object
                properties:
                  users:
                    type: array
                    description: "作成されたユーザー情報の配列"
                    items:
                      $ref: "#/components/schemas/User"

components:
  schemas:
    createEventInput:
      type: object
      properties:
        title:
          type: string
          description: "イベントのタイトル"
        url:
          type: string
          description: "イベントのURL"
      required:
        - title
    createEventResponse:
      type: object
      properties:
        id:
          type: string
          description: "イベントの一意な識別子"
        title:
          type: string
          description: "イベントのタイトル"
        url:
          type: string
          description: "イベントのURL"
        createdAt:
          type: string
          format: date-time
          description: "作成日時"
        updatedAt:
          type: string
          format: date-time
          description: "更新日時"
    User:
      type: object
      properties:
        id:
          type: string
          description: "ユーザーの一意な識別子"
        name:
          type: string
          description: "ユーザーの名前"
        eventId:
          type: string
          description: "関連するイベントの識別子"
      required:
        - id
        - name
        - eventId

