name: LGTM Image Generator

on:
  issue_comment:
    types: [created]

jobs:
  generate-lgtm:
    if: contains(github.event.comment.body, 'lgtm')
    runs-on: ubuntu-latest

    steps:
      - name: Generate LGTM Image
        run: |
          IMAGE_URL="https://lgtm.shinyaigeek.dev/api/lgtm?text=LGTM"
          echo "IMAGE_URL=$IMAGE_URL" >> $GITHUB_ENV

      - name: Post LGTM Image Comment
        uses: peter-evans/create-or-update-comment@v3
        with:
          body: |
            ![LGTM](${{ env.IMAGE_URL }})
          token: ${{ secrets.GITHUB_TOKEN }}
